apiVersion: v1
kind: Service
metadata:
  name: giropops
  labels:
    app: giropops
    run: nginx
    track: stable
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: giropops
  ports:
    - nodePort: 32222
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - nodePort: 32111
      name: prometheus
      port: 32111
      protocol: TCP
      targetPort: 32111
  type: NodePort
  sessionAffinity: None